version: '3.8'
services:
  db:
    image: postgres:14.4
    container_name: telegram-bot-for-gmail-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=telegram-bot-for-gmail-db
    volumes:
      - telegram-bot-for-gmail-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  telegram-bot-for-gmail-db:
    driver: local