# Gmail Configuration
google:
  gmail:
    application-name: Telegram Bot For Gmail
    tokens-path: ${GMAIL_TOKENS_PATH:tokens}
    credentials-path: ${GMAIL_CREDENTIALS_PATH:/credentials/google_credentials.json}
    oauth-url: https://oauth2.googleapis.com/token
    redirect-uri: http://localhost:8080/oauth2callback/
    scopes:
      - https://mail.google.com/

# Telegram Bot Configuration
telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME:GmailCheckerBot}
    token: ${TELEGRAM_BOT_TOKEN}

# Spring Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:telegram-bot-for-gmail-db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 100
  sql:
    init:
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  cache:
    expiration: 60 # in minutes
    initial-capacity: 100
    maximum-size: 500
