# Gmail Configuration
google:
  gmail:
    application-name: Telegram Bot For Gmail
    tokens-path: ${GMAIL_TOKENS_PATH:/tokens}
    credentials-path: ${GMAIL_CREDENTIALS_PATH:/credentials/google_credentials.json}
    oauth-url: https://oauth2.googleapis.com/token
    redirect-uri: http://localhost:8080/oauth2callback/
    scopes:
      - https://mail.google.com/

# Telegram Bot Configuration
telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME:GmailCheckerBot}
    token: ${TELEGRAM_BOT_TOKEN}

spring:
  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:telegram-bot-for-gmail-db}?currentSchema=${DB_SCHEMA:telegram-bot-for-gmail-schema}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 100
  sql:
    init:
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  cache:
    expiration: 60 # in minutes
    initial-capacity: 100
    maximum-size: 500
